# Generated by Django 4.2.5 on 2023-09-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Album',
            new_name='AlbumModel',
        ),
        migrations.RenameModel(
            old_name='Track',
            new_name='TrackModel',
        ),
    ]
