# Generated by Django 4.2.5 on 2023-09-08 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_album_name_albummodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackmodel',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='trackmodel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.albummodel'),
        ),
    ]
